### ISSUE TITLE
Allow faster data loading.

### ISSUE THREAD

**Issue by gostrc** [emirozer/fake2db#16]
I would like to create a table with a million rows or more to stress test a service I am evaluating.

Using a server hosted by aws (rds mysql 5.6), I'm currently using no cpu on my macbook so it is definitely network bound.

I'm able to load about 3000 rows per 5 minutes.
This speed is really slow when you would like to generate a very large table (e.g. many millions of rows)

Some possible suggestions:
1. bulk insert
2. save to a csv, and then call a sql command to load from csv
3. create a pool of connections and insert through each connection

**Comment by gostrc** [comment]
Another update.

I wrote my own program [0] to populate tables pretty quickly using a combination of batching and executemany [1].

Using batches of 20000 records at a time, I was able to achieve about 2500 rows per second.

[0] - https://gist.githubusercontent.com/gostrc/87b73c6bac916ca6de50/raw/86d475f1f7f1c7adb1b13e8cf1948098e686eace/load.py
[1] - http://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-executemany.html

**Comment by emirozer** [comment]
Thank you very much for your detailed input on the speed!

**Comment by emirozer** [comment]
Hey! 
I took your advice about executemany, thank you again!

bde84e18949ded9a7a377f124b693eb0b15d3261

**Comment by emirozer** [comment]
Applied for mysql and sqlite, i will also improve other adapters..
