### ISSUE TITLE
Install shouldn't fail if I don't have pg_config

### ISSUE THREAD

**Issue by benhosmer** [emirozer/fake2db#19]
If I'm working with MySQL or SQLITE, I shouldn't need to install postgresql to use this library. Could this be optional somehow instead?

**Comment by emirozer** [comment]
You are correct on this one, thanks for reporting.

**Comment by mauricioabreu** [comment]
Agreed! :-)

**Comment by benhosmer** [comment]
Thanks for the quick response. Works beautifully now.
