### ISSUE TITLE
Error when running cli

### ISSUE THREAD

**Issue by christabor** [emirozer/fake2db#31]
I tried with and without a virtualenv for dependency isolation, using the following command:

`fake2db --db postgresql --host 0.0.0.0 --port 5632 --password password --username user --rows 10 --name mydb`

Which gave me:

```python
File "/usr/local/bin/fake2db", line 7, in <module>
    from fake2db.fake2db import main
  File "/usr/local/lib/python3.5/site-packages/fake2db/fake2db.py", line 6, in <module>
    from custom import faker_options_container
ImportError: No module named 'custom'
```

But the `custom.py` file exists, it's just not finding it. Installed using pip 9.0.1 and python 2.7.10.

`sudo`  seems to work to bypass the error. Not sure why it needs it, but this is probably unrelated to the specific package, so I'll close this.

**Comment by GustavoAngulo** [comment]
Was this resolved or patched? I am getting the same issue, however the solution suggested (use sudo) is not working.

**Comment by emirozer** [comment]
Hey Gustavo,

I have only heard this from one user whom closed the issue, but if its the case that multiple people are experiencing the same, I am definitely going to take a look at this. 

Will let you know soon...

**Comment by blambin** [comment]
I have this error too,on my cygwin ,msys2 and archlinux .

**Comment by emirozer** [comment]
A new package will be released to the cheese factory soon :)

**Comment by emirozer** [comment]
The latest package should resolve your issues, 

https://pypi.python.org/pypi?:action=display&name=fake2db&version=0.5.2
