### ISSUE TITLE
Missing faker_options_container

### ISSUE THREAD

**Issue by JasonBrannon** [emirozer/fake2db#33]
**SUMMARY:** Followed README, attempted to run fake2db.py but encounter missing dependencies. The following replicates my steps to include confirmation of dependencies: 

**ERROR:**
_ Traceback (most recent call last):
  File "fake2db.py", line 6, in <module>
    from .custom import faker_options_container
ValueError: Attempted relative import in non-package
_

**STEPS:**

**# pip install fake2db**
Requirement already satisfied: fake2db in /Users/jason/Documents/Scripts/fake2db
Requirement already satisfied: fake-factory>=0.5.3 in /usr/local/lib/python2.7/site-packages (from fake2db)

**# pip install psycopg2**
Requirement already satisfied: psycopg2 in /usr/local/lib/python2.7/site-packages

**# cd /Users/jason/Documents/Scripts/fake2db**
**# ls*
LICENSE			docs			fake2db.egg-info	setup.py
README.md		fake2db			requirements.txt

**# pip install -r requirements.txt**
Obtaining file:///Users/jason/Documents/Scripts/fake2db (from -r requirements.txt (line 3))
Requirement already satisfied: fake-factory>=0.5.3 in /usr/local/lib/python2.7/site-packages (from fake2db==0.5.2->-r requirements.txt (line 3))
Installing collected packages: fake2db
  Found existing installation: fake2db 0.5.2
    Uninstalling fake2db-0.5.2:
      Successfully uninstalled fake2db-0.5.2
  Running setup.py develop for fake2db
Successfully installed fake2db

**# cd fake2db**
**# ls**
__init__.py		custom.py		mongodb_handler.py	redis_handler.py
base_handler.py		fake2db.py		mysql_handler.py	sqlite_handler.py
couchdb_handler.py	helpers.py		postgresql_handler.py

**# python fake2db.py --db postgresql --host 127.0.0.1 --port 5432  --password fakepassword --username postgres --name TESTDB --rows 100 --custom address**

Traceback (most recent call last):
  File "fake2db.py", line 6, in <module>
    from .custom import faker_options_container
ValueError: Attempted relative import in non-package

**Comment by emirozer** [comment]
Hi Jason!

Thanks for the report, may i ask a question and an action point if possible:

Q: can you give me information about your python version

Action: when you install fake2db from pip, like you did in the first step, can you try to run your command like this: ```fake2db --db postgresql --host 127.0.0.1 --port 5432 --password fakepassword --username postgres --name TESTDB --rows 100 --custom address```

**Comment by JasonBrannon** [comment]
Emir,

Thanks for the quick response!  Here is the information you requested beginning with Python version:
**Python 2.7.13**

When I run the provided command from the root of the project:
`fake2db --db postgresql --host 127.0.0.1 --port 5432 --password fakepassword --username postgres --name TESTDB --rows 100 --custom address`

**Output:**
```
2017-05-03 08:23:39,916 jason    Rows argument : 100
2017-05-03 08:23:39,930 jason    faker package not found onto python packages, please run :     pip install -r requirements.txt      on the root of the project
```

Interesting, because I had already ran pip install against the requirements.txt from the previous setup steps.

**Comment by emirozer** [comment]
I am able to reproduce this issue, this is a very weird regression as this dependency have never been removed from setup.py ... you can also see fake-factory dependency there.

Thank you very much for the report, i will investigate further and let you know...

**Comment by emirozer** [comment]
Ok i found the issue, apparently the owners of the python package ``fake-factory``  (https://pypi.python.org/pypi/fake-factory) deprecated this library in favor of this package: https://pypi.python.org/pypi/Faker

Long story short, this deprecation by them broke fake2db.

but it should be fixed now so if you can do 

pip uninstall fake2db
and then 
pip install fake2db

everything should be fine
