### ISSUE TITLE
Misprint in column name 'address' in sqlite_handler.data_filler_detailed_registration

### ISSUE THREAD

**Issue by bhrgu** [emirozer/fake2db#39]
'a**d**ress' in CREATE statement at
https://github.com/emirozer/fake2db/blob/7b1b0af20bb7bcbb648e278d12944ab8669f0937/fake2db/sqlite_handler.py#L122

**Comment by emirozer** [comment]
I just released version 0.5.4 to PyPi that contains this fix.
