### ISSUE TITLE
Allow custom schemata

### ISSUE THREAD

**Issue by Californian** [emirozer/fake2db#5]
Let us specify (via a schema.json file or something similar) a custom schemata. Something compatible with https://github.com/topliceanu/mongoose-gen would be great.

**Comment by ligurio** [comment]
Any news?

**Comment by emirozer** [comment]
@ligurio Thank you for the reminder, i totally drifted away into other projects etc.
I will gladly do it but can you provide some feedback on what you would expect from this feature?

Should i follow Californian's advice on mongoose-gen ?

**Comment by ligurio** [comment]
> Should i follow Californian's advice on mongoose-gen ?
Why not? :)

**Comment by emirozer** [comment]
WIP at the moment, will update here. but mongoose-gen is not going to be in, i will stick with fake-factory
